kind: pipeline
name: defaultnewpipe

steps:
- name: publish  
  image: plugins/ecr
  settings:
    repo: drone-test
    registry: 892481148093.dkr.ecr.ap-south-1.amazonaws.com
    region: ap-south-1
    tags:
      - ${DRONE_TAG}

- name: template
  image: alpine
  environment:
      - DRONE_TAG=${DRONE_TAG}
  commands:
      - sed -i "s/COMPLETETAG/${DRONE_TAG}/" termnews.yml
      - cat termnews.yml
