version: '3'
services:
  redis:
      build: ./redis
      expose:
          - "6379"
      
  rabbitmq:
      build: ./rabbitmq
      expose:
          - "5672"
      
  worker:
      build: ./worker
      depends_on:
          - redis
          - rabbitmq

  producer:
      build: ./producer
      ports:
          - "80:80"
      depends_on:
          - worker 
   
  integrationtests:
      build: ./tests
      depends_on: 
          - producer
