version: '3'
services:
  webserver:
    build: ./nginx
    ports:
        - "80:80"
    depends_on:
        - producer
  redis:
      build: ./redis
      expose:
          - "6379"
      
  rabbitmq:
      build: ./rabbitmq
      expose:
          - "5672"
      
  worker:
      build: ./worker
      depends_on:
          - redis
          - rabbitmq

  producer:
      build: ./producer
      expose:
          - "8888"
      depends_on:
          - worker 
    
